# Generated by Django 3.1 on 2020-08-04 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='annotated_images')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shape', models.JSONField()),
                ('class_id', models.CharField(choices=[('caries', 'Caries'), ('stopping', 'Stopping'), ('tooth', 'Tooth')], max_length=24)),
                ('surface', models.CharField(choices=[('b', 'B'), ('l', 'L'), ('o', 'O')], max_length=4)),
                ('meta_confirmed', models.BooleanField(db_index=True, default=False)),
                ('meta_confidence_percent', models.FloatField(db_index=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='images.image')),
            ],
        ),
    ]
